# Generated by Django 5.1.4 on 2025-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
